blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import render_post, post_detail, render_about

app_name = 'blog'
urlpatterns = [
    path('', render_post, name='posts'),
    path('<int:post_id>', post_detail, name="post_detail"),
    path('about/', render_about, name='about' )
]

django_porfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  
from django.conf import settings
from porfolio import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog/', include('blog.urls')),
    path('videos/', include('videos.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videos/urls.py
from django.contrib import admin
from django.urls import path
from .views import upload_video, videos

app_name = 'videos'
urlpatterns = [
    path('videos/upload/', upload_video, name='upload_video'),
    path('videos/', videos, name='videos'),
]

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

porfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField
class Project(models.Model):
    title =  CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portafolio/images/')
    url = URLField(blank=True)
    

videos/models.py
from django.db import models

class Video(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    video_file = models.FileField(upload_to='videos/')
    pub_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title

videos/forms.py
from django import forms
from .models import Video

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['title', 'description', 'video_file']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post 
def render_post(request):
    post = Post.objects.all()
    return render(request, 'post.html', {'posts': post})
def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {"post": post})
def render_about(request):
    about = Post.objects.all()
    return render(request, 'about.html', {'about': about})

porfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, 'home.html', {'projects': projects})

videos/views.py
from django.shortcuts import render, redirect
from .forms import VideoForm
from .models import Video
def upload_video(request):
    if request.method == 'POST':
        form = VideoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('videos:videos')
    else:
        form = VideoForm()
    return render(request, 'videos/upload.html', {'form': form})



def videos(request):
    videos = Video.objects.all()
    return render(request, 'videos/videos.html', {'videos': videos})

blog/templates/about.html
{% extends 'layaout.html' %} {% load static %}
{% block content %}


<section id="about" class="about">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
        <h2>About</h2>
        <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
      </div>
      <div class="row">
        <div class="col-lg-4">
          <img src=" {% static 'porfolio/se.png' %}" class="img-fluid" alt="">
        </div>
        <div class="col-lg-8 pt-4 pt-lg-0 content">
          <h3>UI/UX Designer &amp; Web Developer.</h3>
          <p class="fst-italic">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
            magna aliqua.
          </p>
          <div class="row">
            <div class="col-lg-6">
              <ul>
                <li><i class="bi bi-chevron-right"></i> <strong>Birthday:</strong> <span>1 May 1995</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>Website:</strong> <span>www.example.com</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>Phone:</strong> <span>+123 456 7890</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>City:</strong> <span>New York, USA</span></li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul>
                <li><i class="bi bi-chevron-right"></i> <strong>Age:</strong> <span>30</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>Degree:</strong> <span>Master</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>PhEmailone:</strong> <span>email@example.com</span></li>
                <li><i class="bi bi-chevron-right"></i> <strong>Freelance:</strong> <span>Available</span></li>
              </ul>
            </div>
          </div>
          <p>
            Officiis eligendi itaque labore et dolorum mollitia officiis optio vero. Quisquam sunt adipisci omnis et ut. Nulla accusantium dolor incidunt officia tempore. Et eius omnis.
            Cupiditate ut dicta maxime officiis quidem quia. Sed et consectetur qui quia repellendus itaque neque. Aliquid amet quidem ut quaerat cupiditate. Ab et eum qui repellendus omnis culpa magni laudantium dolores.
          </p>
        </div>
      </div>

    </div>
  </section>
  <section id="resume" class="resume">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
        <h2>Resume</h2>
        <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
      </div>

      <div class="row">
        <div class="col-lg-6">
          <h3 class="resume-title">Sumary</h3>
          <div class="resume-item pb-0">
            <h4>Brandon Johnson</h4>
            <p><em>Innovative and deadline-driven Graphic Designer with 3+ years of experience designing and developing user-centered digital/print marketing material from initial concept to final, polished deliverable.</em></p>
            <ul>
              <li>Portland par 127,Orlando, FL</li>
              <li>(123) 456-7891</li>
              <li>alice.barkley@example.com</li>
            </ul>
          </div>

          <h3 class="resume-title">Education</h3>
          <div class="resume-item">
            <h4>Master of Fine Arts &amp; Graphic Design</h4>
            <h5>2015 - 2016</h5>
            <p><em>Rochester Institute of Technology, Rochester, NY</em></p>
            <p>Qui deserunt veniam. Et sed aliquam labore tempore sed quisquam iusto autem sit. Ea vero voluptatum qui ut dignissimos deleniti nerada porti sand markend</p>
          </div>
          <div class="resume-item">
            <h4>Bachelor of Fine Arts &amp; Graphic Design</h4>
            <h5>2010 - 2014</h5>
            <p><em>Rochester Institute of Technology, Rochester, NY</em></p>
            <p>Quia nobis sequi est occaecati aut. Repudiandae et iusto quae reiciendis et quis Eius vel ratione eius unde vitae rerum voluptates asperiores voluptatem Earum molestiae consequatur neque etlon sader mart dila</p>
          </div>
        </div>
        <div class="col-lg-6">
          <h3 class="resume-title">Professional Experience</h3>
          <div class="resume-item">
            <h4>Senior graphic design specialist</h4>
            <h5>2019 - Present</h5>
            <p><em>Experion, New York, NY </em></p>
            <ul>
              <li>Lead in the design, development, and implementation of the graphic, layout, and production communication materials</li>
              <li>Delegate tasks to the 7 members of the design team and provide counsel on all aspects of the project. </li>
              <li>Supervise the assessment of all graphic materials in order to ensure quality and accuracy of the design</li>
              <li>Oversee the efficient use of production project budgets ranging from $2,000 - $25,000</li>
            </ul>
          </div>
          <div class="resume-item {% static 'porfolio/se.png' %}">
            <h4>Graphic design specialist</h4>
            <h5>2017 - 2018</h5>
            <p><em>Stepping Stone Advertising, New York, NY</em></p>
            <ul>
              <li>Developed numerous marketing programs (logos, brochures,infographics, presentations, and advertisements).</li>
              <li>Managed up to 5 projects or tasks at a given time while under pressure</li>
              <li>Recommended and consulted with clients on the most appropriate graphic design</li>
              <li>Created 4+ design presentations and proposals a month for clients and account managers</li>
            </ul>
          </div>
        </div>
      </div>

    </div>
  </section><!-- End Resume Section -->
{% endblock  %}
    

blog/templates/post.html
{% extends 'layaout.html' %}
{% block content %}
<div class="brl">
    <h1>Blogs</h1>
</div>
    <div class="row   ">
        <div class="d-flex flex-wrap justify-content-center">
            <div class="d-flex  post flex-wrap justify-content-center">
                   
                        {% for post in posts %}
                        <div class="col-md-6 des  ">
                            <div class="card dev mb-3 ">
                                <div class="ses"><img style="" src="{{post.image.url}}" class="img-thumbnail img-fluid card-img-top ses " alt="..."></div>
                                <div class="des">
                                    <h3>{{post.title}}</h3>
                                    <h6 class="card-title til">{{post.date}}</h6>
                                   
                                    <div class="seq">
                                        <p>{{post.description|striptags|truncatechars:100}}</p>
                                    </div>
                                    <div class="botn">
                                    <a  href="{% url 'blog:post_detail' post.id %}" class=" btn btn-primary">Ver</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                       {% endfor %}
                    
            </div>
        </div>
      </div>
      
      
      
    
      
    
  


    
{% endblock  %}

blog/templates/post_detail.html
{% extends 'layaout.html' %} {% block content %}{% load static %}
<div class="tres"><h2>Post</h2>
</div>

<div class="titles"><h1>{{ post.title }}</h1></div>
<div class="d-flex flex-wrap justify-content-center fre">
    <div class="card m-3" style="width: 69rem;">
        
        <h3 class="my-2 h5 text-muted">{{ post.date|date:'F jS Y' }}</h5>
        <div class="wer"><img src="{{ post.image.url }}" alt="" class="img-fluid" /></div>
        <div class="card-body">
        <h5 class="card-title">{{post.title}}</h5>
        <div class="lets"><p>{{ post.description }}|safe</p></div>
        <a href="{% url 'blog:posts' %}" class="btn btn-primary">Ir a Blogs</a>
      </div>
    </div>
    
  </div>
  
{% endblock %}

porfolio/templates/home.html
{% extends 'layaout.html' %} {% block content %}
 
{% load static %}
<section  id="hero" class="d-flex flex-column justify-content-center">
    <div class="container" data-aos="zoom-in" data-aos-delay="100">
      <h1 style="color: white;" >Davis Patrick</h1>
      <p>I'm <span class="typed" data-typed-items="Designer, Developer, Freelancer, Photographer"></span></p>
      <div class="social-links">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= About Section ======= -->
    

<section id="skills" class="skills section-bg">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
        <h2>Skills</h2>
        <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
      </div>

      <div class="row skills-content">

        <div class="col-lg-6">

          <div class="progress">
            <span class="skill">HTML <i class="val">100%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

          <div class="progress">
            <span class="skill">CSS <i class="val">90%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

          <div class="progress">
            <span class="skill">JavaScript <i class="val">35%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="35" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

        </div>

        <div class="col-lg-6">

          <div class="progress">
            <span class="skill">Python <i class="val">40%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

          <div class="progress">
            <span class="skill">django<i class="val">30%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

          <div class="progress">
            <span class="skill">hacking etico<i class="val">23%</i></span>
            <div class="progress-bar-wrap">
              <div class="progress-bar" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>

        </div>

      </div>

    </div>
  </section><!-- End Skills Section -->

  <!-- ======= Resume Section ======= -->
  

  <div class="row my-4 text-center">
    <h3>My Projects</h3>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Maxime, soluta.</p>
{% for project in  projects %}
    
<div class="col-md-4 p-4">
    <div class="card  card-project">
        <img src="{{project.image.url}}  "class='img-top'>
        <div class="card-body ">
            <h2>{{project.title}}</h2>
            

            {% if project.url %}
            <button class="btn btn-primary"><a  href="{{project.url}}" style="color: white;" target="_blanck">ir al enlace</a></button>  

           {% endif %}
        </div>
    </div>
</div>
{% endfor %}
{% endblock  %}

</div>

porfolio/templates/layaout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="https://kit.fontawesome.com/3f4a6cbae5.css" crossorigin="anonymous">
    <link href=" {% static '/img/sert.png' %} " rel="icon">
  <link href="{% static '/img/apple-touch-icon.png ' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap" 

  <!-- Vendor CSS Files -->
  <link href="{% static '/vendor/aos/aos.css' %} " rel="stylesheet">
  <link href=" {% static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href=" {% static '/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css {% static '/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="assets/vendor/glightbox/css/glightbox.min.css {% static '/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="assets/vendor/swiper/swiper-bundle.min.css {% static '/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href=" {% static 'style.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans&display=swap" rel="stylesheet">
    <title>Django</title>
</head>
<body class='text-dark '>
    {% include 'partials/navbar.html' %}
    

    {% block content %}
    
        
    {% endblock %}

   
    {% include 'partials/Footer.html'%}



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static '/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static '/vendor/aos/aos.js' %}"></script>
  <script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static '/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static '/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static '/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static '/vendor/typed.js/typed.min.js' %}"></script>
  <script src="{% static '/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src=" {% static '/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src=" {% static '/js/main.js' %} "></script>
  <script src="https://kit.fontawesome.com/3f4a6cbae5.js" crossorigin="anonymous"></script>
</body>
</html>

porfolio/templates/partials/Footer.html
<footer  class="mt-5 de" id="footer">
  <div class="container  de mt4">
    <h3>Davis Pratick</h3>
    <p>Et aut eum quis fuga eos sunt ipsa nihil. Labore corporis magni eligendi fuga maxime saepe commodi placeat.</p>
    <div class="social-links">
      <a href="https://twitter.com/PatrikPE1" class="twitter"><i class="fa-brands fa-twitter bx bxl-twitter"></i></a>
      <a href="https://www.facebook.com/gringoanonim/" class="facebook"><i class="fa-brands fa-square-facebook bx bxl-facebook"></i></a>
      <a href="https://www.instagram.com/davis_patrick_men/" class="instagram"><i class=" fa-brands fa-instagram bx bxl-instagram"></i></a>
      <a href="https://www.youtube.com/channel/UCVQ6Br8dbY4jONpP1JveRow" class="google-plus"><i class="fa-brands fa-youtube bx bxl-skype"></i></a>
      <a href="https://github.com/Sherklan12e" class="linkedin"><i class="fa-brands fa-github bx bxl-linkedin"></i></a>
      
    </div>
    <div class="copyright">
      &copy; Copyright <strong><span>MyResume</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: [license-url] -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/ -->
      Designed by <a href="https://www.youtube.com/channel/UCVQ6Br8dbY4jONpP1JveRow">PatrickPe</a>
    </div>
  </div>
</footer><!-- End Footer -->
<div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

porfolio/templates/partials/navbar.html
{% load static %}

<header id="header" class="d-flex flex-column justify-content-center">

  <nav id="navbar" class="navbar nav-menu">
    <ul>
      <li><a href="/" class="nav-link scrollto active"><i class="fa-solid fa-house bx bx-home"></i> <span>Home</span></a></li>
      <li><a href="{% url 'blog:about' %}" class="nav-link scrollto"><i class="fa-solid fa-user bx bx-user"></i> <span>About</span></a></li>
      
      <li><a href="{% url 'blog:posts' %}" class="nav-link scrollto"><i class="fa-solid fa-image"></i> <span>Blog</span></a></li>
      <li><a href="{% url 'videos:videos' %}" class="nav-link scrollto"><i class="fa-solid fa-image"></i> <span>Videos</span></a></li>
      <li><a href="{% url 'videos:upload_video' %}" class="nav-link scrollto"><i class="fa-solid fa-image"></i> <span>Subir Video</span></a></li>
    </ul>
  </nav><!-- .nav-menu -->

</header>

videos/templates/videos/upload.html
{% extends 'layaout.html' %}

{% block content %}
  <div class="brl">
    <h1>Subir Video</h1>
  </div>
  
  <form class="gut" method="post" >
    {% csrf_token %}
    <div class=" sr mb-3">
      {{ form.title }}
      
      <div id="emailHelp" class="form-text">Escribe el Titulo del video</div>
    </div>
    <div class=" sd mb-3">
      {{ form.description }}
      <div id="emailHelp" class="form-text">Escribe la descripcion del video</div>

      
    </div>
    <div class=" sp mb-3 form-check">
      <div>{{ form.video_file }}
        {{ form.video_file.label_tag }}</div>
    </div>
    <div class="peq"><button  type="submit" class="btn ss btn-primary">Submit</button></div>
  </form>
  
  
  
{% endblock %}

videos/templates/videos/videos.html
{% extends 'layaout.html' %}

{% block content %}
  <div class="brl">
    <h1>Videos</h1>
  </div>
  <div class="row   ">
    <div class="d-flex flex-wrap justify-content-center">
        <div class="d-flex  post flex-wrap justify-content-center">
               
                    {% for video in videos %}
                     <div class="col-md-6 des  ">
                          <div class="card dev mb-3 ">
                             <div class="sess"><video controls style="width: 500px;">
                                <source src="{{ video.video_file.url }}" type="video/mp4">
                             </video></div>
                             <div class="des">
                                 <h3>{{ video.title }}</h3>
                                  <h6 class="card-title til"></h6>
                               
                                 <div class="seq">
                                     <p>{{ video.description }}</p>
                                 </div>
                                 
                            </div>
                        </div>
                      </div>
                   {% endfor %}
                
        </div>
    </div>
  </div>
{% endblock %}